export default async function getRooms(queryString: string) {
    // return serverFetch(`/books?${queryString}`);
    return [
  {
    "_id": "space_001",
    "title": "Downtown Hub Co-working",
    "shortDescription": "Modern co-working space with high-speed internet, ergonomic desks, and a vibrant community atmosphere.",
    "images": ["https://picsum.photos/id/1015/800/600", "https://picsum.photos/id/1016/800/600"],
    "category": "Co-working",
    "location": "123 Gulshan Avenue",
    "city": "Dhaka",
    "pricePerHour": 450,
    "capacity": 50,
    "rating": 4.7,
    "reviewCount": 128
  },
  {
    "_id": "space_002",
    "title": "Executive Meeting Room",
    "shortDescription": "Fully equipped meeting room with 65-inch display, video conferencing, and premium seating.",
    "images": ["https://picsum.photos/id/102/800/600"],
    "category": "Meeting Room",
    "location": "45 Banani Road, Block D",
    "city": "Dhaka",
    "pricePerHour": 850,
    "capacity": 12,
    "rating": 4.9,
    "reviewCount": 67
  },
  {
    "_id": "space_003",
    "title": "Grand Ballroom Event Hall",
    "shortDescription": "Spacious hall perfect for weddings, conferences, and large corporate events with stage and lighting.",
    "images": ["https://picsum.photos/id/1033/800/600", "https://picsum.photos/id/1040/800/600", "https://picsum.photos/id/106/800/600"],
    "category": "Event Hall",
    "location": "Sector 10, Uttara",
    "city": "Dhaka",
    "pricePerHour": 2500,
    "capacity": 300,
    "rating": 4.5,
    "reviewCount": 89
  },
  {
    "_id": "space_004",
    "title": "Creative Photo & Video Studio",
    "shortDescription": "Professional photography studio with natural light, backdrop options, and professional lighting setup.",
    "images": ["https://picsum.photos/id/1074/800/600", "https://picsum.photos/id/133/800/600"],
    "category": "Studio",
    "location": "Mirpur-10, Road 5",
    "city": "Dhaka",
    "pricePerHour": 1200,
    "capacity": 8,
    "rating": 4.8,
    "reviewCount": 54
  },
  {
    "_id": "space_005",
    "title": "The Loft Co-working",
    "shortDescription": "Industrial-style co-working space with open layout, private pods, and rooftop terrace.",
    "images": ["https://picsum.photos/id/201/800/600"],
    "category": "Co-working",
    "location": "Gulshan-2, House 45",
    "city": "Dhaka",
    "pricePerHour": 380,
    "capacity": 35,
    "rating": 4.6,
    "reviewCount": 112
  },
  {
    "_id": "space_006",
    "title": "Boardroom Premium",
    "shortDescription": "Luxury meeting room featuring leather chairs, smart TV, and white board with video call facility.",
    "images": ["https://picsum.photos/id/251/800/600", "https://picsum.photos/id/256/800/600"],
    "category": "Meeting Room",
    "location": "Dhanmondi 27",
    "city": "Dhaka",
    "pricePerHour": 950,
    "capacity": 18,
    "rating": 4.4,
    "reviewCount": 41
  },
  {
    "_id": "space_007",
    "title": "Riverside Event Venue",
    "shortDescription": "Beautiful open hall with river view, ideal for product launches, parties, and seminars.",
    "images": ["https://picsum.photos/id/1018/800/600", "https://picsum.photos/id/133/800/600"],
    "category": "Event Hall",
    "location": "Savar, Near Ashulia",
    "city": "Dhaka",
    "pricePerHour": 1800,
    "capacity": 150,
    "rating": 4.3,
    "reviewCount": 76
  },
  {
    "_id": "space_008",
    "title": "Music & Podcast Studio",
    "shortDescription": "Soundproof recording studio equipped with high-end microphones, mixing console, and acoustic treatment.",
    "images": ["https://picsum.photos/id/870/800/600"],
    "category": "Studio",
    "location": "Mohammadpur, Block E",
    "city": "Dhaka",
    "pricePerHour": 1400,
    "capacity": 6,
    "rating": 4.9,
    "reviewCount": 33
  },
  {
    "_id": "space_009",
    "title": "Silicon Valley Co-working",
    "shortDescription": "Tech-focused co-working space with fast fiber internet, meeting pods, and networking events.",
    "images": ["https://picsum.photos/id/180/800/600", "https://picsum.photos/id/201/800/600"],
    "category": "Co-working",
    "location": "Gulshan-1, Road 12",
    "city": "Dhaka",
    "pricePerHour": 520,
    "capacity": 65,
    "rating": 4.8,
    "reviewCount": 145
  },
  {
    "_id": "space_010",
    "title": "Skyline Conference Room",
    "shortDescription": "Stunning 10th-floor meeting room with city view and all modern AV facilities.",
    "images": ["https://picsum.photos/id/1015/800/600"],
    "category": "Meeting Room",
    "location": "Tejgaon Industrial Area",
    "city": "Dhaka",
    "pricePerHour": 1100,
    "capacity": 25,
    "rating": 4.7,
    "reviewCount": 52
  },
  {
    "_id": "space_011",
    "title": "The Pavilion Event Hall",
    "shortDescription": "Elegant multi-purpose hall with excellent acoustics and flexible seating arrangements.",
    "images": ["https://picsum.photos/id/133/800/600", "https://picsum.photos/id/160/800/600"],
    "category": "Event Hall",
    "location": "Bashundhara Residential Area",
    "city": "Dhaka",
    "pricePerHour": 2200,
    "capacity": 220,
    "rating": 4.6,
    "reviewCount": 68
  },
  {
    "_id": "space_012",
    "title": "Artisan Creative Studio",
    "shortDescription": "Bright and airy studio perfect for photoshoots, content creation, and small workshops.",
    "images": ["https://picsum.photos/id/201/800/600", "https://picsum.photos/id/251/800/600"],
    "category": "Studio",
    "location": "Banani DOHS",
    "city": "Dhaka",
    "pricePerHour": 950,
    "capacity": 10,
    "rating": 4.9,
    "reviewCount": 47
  },
  {
    "_id": "space_013",
    "title": "Green Leaf Co-working",
    "shortDescription": "Eco-friendly co-working space with plants, natural lighting, and quiet zones.",
    "images": ["https://picsum.photos/id/133/800/600"],
    "category": "Co-working",
    "location": "Uttara Sector 13",
    "city": "Dhaka",
    "pricePerHour": 420,
    "capacity": 40,
    "rating": 4.5,
    "reviewCount": 93
  },
  {
    "_id": "space_014",
    "title": "Corporate Strategy Room",
    "shortDescription": "Premium meeting room designed for board meetings and high-level discussions.",
    "images": ["https://picsum.photos/id/106/800/600", "https://picsum.photos/id/107/800/600"],
    "category": "Meeting Room",
    "location": "Gulshan Circle 2",
    "city": "Dhaka",
    "pricePerHour": 1300,
    "capacity": 15,
    "rating": 4.8,
    "reviewCount": 39
  },
  {
    "_id": "space_015",
    "title": "Heritage Grand Hall",
    "shortDescription": "Classic elegant event hall with chandeliers and traditional-modern fusion design.",
    "images": ["https://picsum.photos/id/1018/800/600"],
    "category": "Event Hall",
    "location": "Old Dhaka, Near Ahsanullah Road",
    "city": "Dhaka",
    "pricePerHour": 2800,
    "capacity": 280,
    "rating": 4.4,
    "reviewCount": 71
  },
  {
    "_id": "space_016",
    "title": "YouTube & Reel Studio",
    "shortDescription": "Modern content creation studio with ring lights, green screen, and 4K camera setup.",
    "images": ["https://picsum.photos/id/870/800/600", "https://picsum.photos/id/133/800/600"],
    "category": "Studio",
    "location": "Mirpur-2, Block C",
    "city": "Dhaka",
    "pricePerHour": 1150,
    "capacity": 7,
    "rating": 4.7,
    "reviewCount": 64
  },
  {
    "_id": "space_017",
    "title": "Innovation Hub",
    "shortDescription": "Spacious collaborative workspace with brainstorming areas and high-tech amenities.",
    "images": ["https://picsum.photos/id/201/800/600"],
    "category": "Co-working",
    "location": "Baridhara Diplomatic Zone",
    "city": "Dhaka",
    "pricePerHour": 600,
    "capacity": 55,
    "rating": 4.6,
    "reviewCount": 81
  },
  {
    "_id": "space_018",
    "title": "VIP Meeting Suite",
    "shortDescription": "Private luxurious meeting suite with lounge area and full catering support.",
    "images": ["https://picsum.photos/id/251/800/600"],
    "category": "Meeting Room",
    "location": "Gulshan-2, House 78",
    "city": "Dhaka",
    "pricePerHour": 1650,
    "capacity": 10,
    "rating": 4.9,
    "reviewCount": 28
  },
  {
    "_id": "space_019",
    "title": "Urban Festival Hall",
    "shortDescription": "Versatile large hall suitable for exhibitions, cultural events, and corporate galas.",
    "images": ["https://picsum.photos/id/1033/800/600", "https://picsum.photos/id/1040/800/600"],
    "category": "Event Hall",
    "location": "Khilgaon, Taltola",
    "city": "Dhaka",
    "pricePerHour": 1950,
    "capacity": 180,
    "rating": 4.5,
    "reviewCount": 55
  },
  {
    "_id": "space_020",
    "title": "Film & Photography Studio Pro",
    "shortDescription": "Large studio with cyclorama wall, professional lighting, and makeup station.",
    "images": ["https://picsum.photos/id/870/800/600"],
    "category": "Studio",
    "location": "Mohakhali, Wireless Gate",
    "city": "Dhaka",
    "pricePerHour": 1600,
    "capacity": 12,
    "rating": 4.8,
    "reviewCount": 49
  },
  {
    "_id": "space_004",
    "title": "Creative Photo & Video Studio",
    "shortDescription": "Professional photography studio with natural light, backdrop options, and professional lighting setup.",
    "images": ["https://picsum.photos/id/1074/800/600", "https://picsum.photos/id/133/800/600"],
    "category": "Studio",
    "location": "Mirpur-10, Road 5",
    "city": "Dhaka",
    "pricePerHour": 1200,
    "capacity": 8,
    "rating": 4.8,
    "reviewCount": 54
  },
  {
    "_id": "space_005",
    "title": "The Loft Co-working",
    "shortDescription": "Industrial-style co-working space with open layout, private pods, and rooftop terrace.",
    "images": ["https://picsum.photos/id/201/800/600"],
    "category": "Co-working",
    "location": "Gulshan-2, House 45",
    "city": "Dhaka",
    "pricePerHour": 380,
    "capacity": 35,
    "rating": 4.6,
    "reviewCount": 112
  },
  {
    "_id": "space_006",
    "title": "Boardroom Premium",
    "shortDescription": "Luxury meeting room featuring leather chairs, smart TV, and white board with video call facility.",
    "images": ["https://picsum.photos/id/251/800/600", "https://picsum.photos/id/256/800/600"],
    "category": "Meeting Room",
    "location": "Dhanmondi 27",
    "city": "Dhaka",
    "pricePerHour": 950,
    "capacity": 18,
    "rating": 4.4,
    "reviewCount": 41
  },
  {
    "_id": "space_007",
    "title": "Riverside Event Venue",
    "shortDescription": "Beautiful open hall with river view, ideal for product launches, parties, and seminars.",
    "images": ["https://picsum.photos/id/1018/800/600", "https://picsum.photos/id/133/800/600"],
    "category": "Event Hall",
    "location": "Savar, Near Ashulia",
    "city": "Dhaka",
    "pricePerHour": 1800,
    "capacity": 150,
    "rating": 4.3,
    "reviewCount": 76
  },
  {
    "_id": "space_008",
    "title": "Music & Podcast Studio",
    "shortDescription": "Soundproof recording studio equipped with high-end microphones, mixing console, and acoustic treatment.",
    "images": ["https://picsum.photos/id/870/800/600"],
    "category": "Studio",
    "location": "Mohammadpur, Block E",
    "city": "Dhaka",
    "pricePerHour": 1400,
    "capacity": 6,
    "rating": 4.9,
    "reviewCount": 33
  },
  {
    "_id": "space_009",
    "title": "Silicon Valley Co-working",
    "shortDescription": "Tech-focused co-working space with fast fiber internet, meeting pods, and networking events.",
    "images": ["https://picsum.photos/id/180/800/600", "https://picsum.photos/id/201/800/600"],
    "category": "Co-working",
    "location": "Gulshan-1, Road 12",
    "city": "Dhaka",
    "pricePerHour": 520,
    "capacity": 65,
    "rating": 4.8,
    "reviewCount": 145
  },
  {
    "_id": "space_010",
    "title": "Skyline Conference Room",
    "shortDescription": "Stunning 10th-floor meeting room with city view and all modern AV facilities.",
    "images": ["https://picsum.photos/id/1015/800/600"],
    "category": "Meeting Room",
    "location": "Tejgaon Industrial Area",
    "city": "Dhaka",
    "pricePerHour": 1100,
    "capacity": 25,
    "rating": 4.7,
    "reviewCount": 52
  },
  {
    "_id": "space_011",
    "title": "The Pavilion Event Hall",
    "shortDescription": "Elegant multi-purpose hall with excellent acoustics and flexible seating arrangements.",
    "images": ["https://picsum.photos/id/133/800/600", "https://picsum.photos/id/160/800/600"],
    "category": "Event Hall",
    "location": "Bashundhara Residential Area",
    "city": "Dhaka",
    "pricePerHour": 2200,
    "capacity": 220,
    "rating": 4.6,
    "reviewCount": 68
  },
  {
    "_id": "space_012",
    "title": "Artisan Creative Studio",
    "shortDescription": "Bright and airy studio perfect for photoshoots, content creation, and small workshops.",
    "images": ["https://picsum.photos/id/201/800/600", "https://picsum.photos/id/251/800/600"],
    "category": "Studio",
    "location": "Banani DOHS",
    "city": "Dhaka",
    "pricePerHour": 950,
    "capacity": 10,
    "rating": 4.9,
    "reviewCount": 47
  },
  {
    "_id": "space_013",
    "title": "Green Leaf Co-working",
    "shortDescription": "Eco-friendly co-working space with plants, natural lighting, and quiet zones.",
    "images": ["https://picsum.photos/id/133/800/600"],
    "category": "Co-working",
    "location": "Uttara Sector 13",
    "city": "Dhaka",
    "pricePerHour": 420,
    "capacity": 40,
    "rating": 4.5,
    "reviewCount": 93
  },
  {
    "_id": "space_014",
    "title": "Corporate Strategy Room",
    "shortDescription": "Premium meeting room designed for board meetings and high-level discussions.",
    "images": ["https://picsum.photos/id/106/800/600", "https://picsum.photos/id/107/800/600"],
    "category": "Meeting Room",
    "location": "Gulshan Circle 2",
    "city": "Dhaka",
    "pricePerHour": 1300,
    "capacity": 15,
    "rating": 4.8,
    "reviewCount": 39
  },
  {
    "_id": "space_015",
    "title": "Heritage Grand Hall",
    "shortDescription": "Classic elegant event hall with chandeliers and traditional-modern fusion design.",
    "images": ["https://picsum.photos/id/1018/800/600"],
    "category": "Event Hall",
    "location": "Old Dhaka, Near Ahsanullah Road",
    "city": "Dhaka",
    "pricePerHour": 2800,
    "capacity": 280,
    "rating": 4.4,
    "reviewCount": 71
  },
  {
    "_id": "space_016",
    "title": "YouTube & Reel Studio",
    "shortDescription": "Modern content creation studio with ring lights, green screen, and 4K camera setup.",
    "images": ["https://picsum.photos/id/870/800/600", "https://picsum.photos/id/133/800/600"],
    "category": "Studio",
    "location": "Mirpur-2, Block C",
    "city": "Dhaka",
    "pricePerHour": 1150,
    "capacity": 7,
    "rating": 4.7,
    "reviewCount": 64
  },
  {
    "_id": "space_017",
    "title": "Innovation Hub",
    "shortDescription": "Spacious collaborative workspace with brainstorming areas and high-tech amenities.",
    "images": ["https://picsum.photos/id/201/800/600"],
    "category": "Co-working",
    "location": "Baridhara Diplomatic Zone",
    "city": "Dhaka",
    "pricePerHour": 600,
    "capacity": 55,
    "rating": 4.6,
    "reviewCount": 81
  },
  {
    "_id": "space_018",
    "title": "VIP Meeting Suite",
    "shortDescription": "Private luxurious meeting suite with lounge area and full catering support.",
    "images": ["https://picsum.photos/id/251/800/600"],
    "category": "Meeting Room",
    "location": "Gulshan-2, House 78",
    "city": "Dhaka",
    "pricePerHour": 1650,
    "capacity": 10,
    "rating": 4.9,
    "reviewCount": 28
  },
  {
    "_id": "space_019",
    "title": "Urban Festival Hall",
    "shortDescription": "Versatile large hall suitable for exhibitions, cultural events, and corporate galas.",
    "images": ["https://picsum.photos/id/1033/800/600", "https://picsum.photos/id/1040/800/600"],
    "category": "Event Hall",
    "location": "Khilgaon, Taltola",
    "city": "Dhaka",
    "pricePerHour": 1950,
    "capacity": 180,
    "rating": 4.5,
    "reviewCount": 55
  },
  {
    "_id": "space_020",
    "title": "Film & Photography Studio Pro",
    "shortDescription": "Large studio with cyclorama wall, professional lighting, and makeup station.",
    "images": ["https://picsum.photos/id/870/800/600"],
    "category": "Studio",
    "location": "Mohakhali, Wireless Gate",
    "city": "Dhaka",
    "pricePerHour": 1600,
    "capacity": 12,
    "rating": 4.8,
    "reviewCount": 49
  }
];
}